### PR TITLE
Updated `estraverse`. Added tests for optional chaining support

### PR DESCRIPTION
**Pull request by sanex3339**
Updated `estraverse`. Added tests for optional chaining support.
@michaelficarra please check this. This PR is high-priority for me.

### CODE REVIEW

**Comment by sanex3339** [comment]
@michaelficarra It would be nice to get this merged because without it I have to use `resolutions` section of `yarn` to install the latest `estraverse` version for `esrecurse`. Thank you!

**Comment by sanex3339** [comment]
@michaelficarra  Ping. Please check this small PR.

**Review by nzakas — APPROVED** [review]

**Comment by sanex3339** [comment]
@michaelficarra may you merge this please?

**Comment by nzakas** [comment]
I don’t think he’s maintaining this any more. I can merge the PR and it appears I can cut a new release but I’ll have to figure out how that works.

**Comment by michaelficarra** [comment]
@nzakas Let me know if you have any questions. The release process should be the same as the other estools/* projects.

**Comment by sanex3339** [comment]
@nzakas @michaelficarra thank you!

**Comment by sanex3339** [comment]
@michaelficarra i don't see any scripts like `publish` or `release` in the package.json like `escodegen` has.
@nzakas so looks like you have to increase version number manually and publish package manually too. Am i wrong?

UPD: i saw few gulp task:
```
gulp.task('patch', [ ], () => inc('patch'));
gulp.task('minor', [ ], () => inc('minor'));
gulp.task('major', [ ], () => inc('major'));
```

**Comment by michaelficarra** [comment]
1. `git checkout master`
1. `git pull`
1. `git clean -fd`
1. Bump the version (in this case I think it'd be minor)
1. `npm install`
1. `npm test`
1. `git commit -m 'Version X.Y.Z' -- package.json`
1. `npm publish`
1. `npm tag -a vX.Y.Z -m 'Version X.Y.Z'`
1. `git push --follow-tags`

**Comment by nzakas** [comment]
Thanks @michaelficarra. I’ll try to get to this later this week

**Comment by sanex3339** [comment]
@nzakas any news?

**Comment by nzakas** [comment]
No sorry, things are a bit crazy in California and this is low priority for me right now. I will get to it when I can. Thanks for your patience.

**Comment by sanex3339** [comment]
That's sad =( Anybody else can release this? @Constellation @michaelficarra

**Comment by michaelficarra** [comment]
@sanex3339 published `4.3.0`

**Comment by sanex3339** [comment]
Thank you!

**Pull request merged**
