### PR TITLE
Use HTTP"S" URL as possible

### PR DESCRIPTION
**Pull request by shinnn**
[Web Security: Why You Should Always Use HTTPS](http://mashable.com/2011/05/31/https-web-security/)

### CODE REVIEW

**Comment by Constellation** [comment]
lgtm

**Comment by shinnn** [comment]
I'll resolve merge conflict soon.

**Comment by Constellation** [comment]
OK, after solving the conflict, I'll merge this :)

**Comment by shinnn** [comment]
2fb3d9183f096adc03c84049786f297c627b3fb6

**Comment by Constellation** [comment]
LGTM

**Comment by Constellation** [comment]
Thanks :)

**Pull request merged**
